apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-deploy
  name: test-deploy
spec:
  replicas: 12
  selector:
    matchLabels:
      app: test-deploy
  template:
    metadata:
      labels:
        app: test-deploy
    spec:
      containers:
       - image: httpd:alpine3.13
         name: httpd
         command: ["/bin/bash", "-c"] # override the default command
         args: ["sleep 5; exit 1"] # sleep for 30 seconds then exit with an error
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 1
       maxSurge: 1

